spring.application.name=SpringBootWebFlux_PracticalMidterm_TrushaMavani
logging.level.org.springframework=ERROR
logging.level.com=TRACE

server.port=8084

spring.mongodb.host=localhost
spring.mongodb.port=27017
spring.mongodb.database=humber